DROP TABLE IF EXISTS company;
CREATE TABLE company (
  `company_id` int auto_increment PRIMARY KEY COMMENT '公司自增ID',
  `company_full_name` varchar(32) NOT NULL COMMENT '公司全称',
  `company_name` varchar(32) COMMENT '公司简称',
  `company_size` varchar(8) COMMENT '公司规模',
  `contact` varchar(8) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(16) NOT NULL COMMENT '联系电话',
  `contact_position` varchar(8) COMMENT '联系人职位',
  `province_code` varchar(8) NOT NULL COMMENT '省级ID',
  `province_name` varchar(8) NOT NULL COMMENT '省级名称',
  `city_code` varchar(8) NOT NULL COMMENT '市级ID',
  `city_name` varchar(8) NOT NULL COMMENT '市级名称',
  `county_code` varchar(8) NOT NULL COMMENT '县级ID',
  `county_name` varchar(8) NOT NULL COMMENT '县级名称',
  `address` varchar(64) NOT NULL COMMENT '详细地址',
  `company_profile` varchar(256) COMMENT '公司简介',
  `company_business_license` varchar(32) COMMENT '营业执照图片ID',
  `company_logo` varchar(32) COMMENT '公司logo图片ID',
  `company_pic` varchar(32) COMMENT '营业照片图片ID',
  `company_type_id` varchar(32) NOT NULL COMMENT '公司类型ID',
  `company_type_name` varchar(32) NOT NULL COMMENT '公司类型名称',
  `parentId` varchar(32) NOT NULL COMMENT '上级公司ID -1:顶级',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;