DROP TABLE IF EXISTS labor_demand;
CREATE TABLE labor_demand (
  `laborDemandId` int auto_increment PRIMARY KEY COMMENT '用工需求自增ID',
  `company_id` varchar(8) NOT NULL COMMENT '公司ID',
  `company_full_name` varchar(32) NOT NULL COMMENT '公司名称',
  `demandId` varchar(16) UNIQUE NOT NULL COMMENT '需求编号',
  `demandSource` varchar(32) NOT NULL COMMENT '需求来源',
  `demandSourceTypeId` varchar(8) NOT NULL COMMENT '需求来源类型ID',
  `demandSourceName` varchar(32) NOT NULL COMMENT '需求来源公司名称',
  `demandSourceId` varchar(8) NOT NULL COMMENT '需求来源公司ID',
  `usingCompanyId` varchar(8) NOT NULL COMMENT '用工公司ID',
  `usingCompanyName` varchar(32) NOT NULL COMMENT '用工公司名称',
  `stationName` varchar(16) NOT NULL COMMENT '岗位名称',
  `salaryTypeId` varchar(16) NOT NULL COMMENT '薪酬类型ID',
  `salaryTypeName` varchar(16) NOT NULL COMMENT '薪酬类型名称',
  `province_code` varchar(8) NOT NULL COMMENT '省级ID',
  `province_name` varchar(8) NOT NULL COMMENT '省级名称',
  `city_code` varchar(8) NOT NULL COMMENT '市级ID',
  `city_name` varchar(8) NOT NULL COMMENT '市级名称',
  `county_code` varchar(8) NOT NULL COMMENT '县级ID',
  `county_name` varchar(8) NOT NULL COMMENT '县级名称',
  `address` varchar(64) NOT NULL COMMENT '详细地址',
  `startWorkTime` varchar(20) NOT NULL COMMENT '工作周期起始时间',
  `endWorkTime` varchar(20) NOT NULL COMMENT '工作周期结束时间',
  `resident` varchar(8) NOT NULL COMMENT '驻场ID',
  `residentName` varchar(12) NOT NULL COMMENT '驻场名称',
  `minAge` varchar(3) COMMENT '最小年龄',
  `maxAge` varchar(3) COMMENT '最大年龄',
  `genderName` varchar(4) COMMENT '性别',
  `genderId` varchar(8) COMMENT '性别ID',
  `shiftSystemName` varchar(16) COMMENT '班制名称',
  `shiftSystemId` varchar(8) COMMENT '班制ID',
  `operationModeName` varchar(16) COMMENT '工作方式名称',
  `operationModeId` varchar(8) COMMENT '工作方式ID',
  `workClothesName` varchar(16) COMMENT '工衣名称',
  `workClothesId` varchar(8) COMMENT '工衣ID',
  `welfareMemberId` varchar(32) COMMENT '福利因素ID',
  `welfareMembers` varchar(1024) COMMENT '福利因素',
  `features` varchar(30) COMMENT '特色描述',
  `jobRequirements` varchar(512) NOT NULL COMMENT '岗位要求',
  `businessPriceId` varchar(8) NOT NULL COMMENT '业务价ID',
  `businessPriceName` varchar(8) NOT NULL COMMENT '业务价名称',
  `signUnitPrice` varchar(16) NOT NULL COMMENT '签单价',
  `businessFunds` varchar(16) COMMENT '业务款',
  `workersPrice` varchar(16) NOT NULL COMMENT '工人价',
  `status` varchar(2) NOT NULL DEFAULT 0 COMMENT '状态 0:未发布 1:发布中',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;