DROP TABLE IF EXISTS user_job;
CREATE TABLE user_job (
  `userJobId` int auto_increment PRIMARY KEY COMMENT '用户工作岗位自增ID',
  `user_id` varchar(12) COMMENT '用户ID',
  `user_company_id` varchar(12) COMMENT '用户公司ID',
  `company_id` varchar(12) COMMENT '公司ID',
  `company_full_name` varchar(32) COMMENT '公司全称',
  `startJobTime` varchar(20) COMMENT '入职时间',
  `endJobTime` varchar(20) COMMENT '离职结束时间',
  `promoteTeamId` varchar(12) COMMENT '推荐团队Id',
  `promoteTeam` varchar(32) COMMENT '推荐团队',
  `resident` varchar(8) COMMENT '驻场ID',
  `residentName` varchar(12) COMMENT '驻场名称',
  `province_code` varchar(8) COMMENT '省级ID',
  `province_name` varchar(8) COMMENT '省级名称',
  `city_code` varchar(8) COMMENT '市级ID',
  `city_name` varchar(8) COMMENT '市级名称',
  `county_code` varchar(8) COMMENT '县级ID',
  `county_name` varchar(8) COMMENT '县级名称',
  `address` varchar(64) COMMENT '详细地址',
  `usingCompanyId` varchar(12) COMMENT '用工公司ID',
  `usingCompanyName` varchar(32) COMMENT '用工公司名称',
  `stationName` varchar(16) COMMENT '岗位名称',
  `workersPrice` varchar(16) COMMENT '工人价',
  `salaryTypeId` varchar(16) COMMENT '薪酬类型ID',
  `salaryTypeName` varchar(16) COMMENT '薪酬类型名称',
  `shiftSystemName` varchar(16) COMMENT '班制名称',
  `shiftSystemId` varchar(8) COMMENT '班制ID',
  `operationModeName` varchar(16) COMMENT '工作方式名称',
  `operationModeId` varchar(8) COMMENT '工作方式ID',
  `workClothesName` varchar(16) COMMENT '工衣名称',
  `workClothesId` varchar(8) COMMENT '工衣ID',
  `welfareMemberId` varchar(32) COMMENT '福利因素ID',
  `welfareMembers` varchar(1024) COMMENT '福利因素',
  `startWorkTime` varchar(20) COMMENT '工作周期起始时间',
  `endWorkTime` varchar(20) COMMENT '工作周期结束时间',
  `jobRequirements` varchar(512) COMMENT '岗位要求',
  `jobStatusId` varchar(16) COMMENT '工作状态ID',
  `jobStatus` varchar(16) COMMENT '工作状态',
  `jobStatusTypeId` varchar(16) COMMENT '工作状态类型ID',
  `jobStatusType` varchar(16) COMMENT '工作状态类型',
  `jobStatusReasonId` varchar(16) COMMENT '工作状态原因ID',
  `jobStatusReason` varchar(16) COMMENT '工作状态原因',
  `jobStatusExplain` varchar(512) COMMENT '工作状态说明',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;